= Getting Started with Red Hat Connectivity Link
:navtitle: Home

== Introduction

Welcome to this quick course on the _Getting Started with Red Hat Connectivity Link_.
This course is the `second` in a series of `two` courses about Red Hat Connectivity Link (RHCL):

* https://xyz.com/[_Introduction to Red Hat Connectivity Link_]
* Getting Started with Red Hat Connectivity Link (_This course_)

== What's in this course?

* This lab is designed to use Red Hat Connectivity Link (RHCL) with a specific use case to implement its features, focusing on three different user roles:

** **Infrastructure Engineer**: As a Infrastructure Engineer, this lab will guide through Kuadrant installation and configuration.

** **Platform Engineer**: As a Platform Engineer, this lab will guide you through deploying a Gateway that ensures secure communication, making it ready for application development teams. You'll learn to route specific traffic while maintaining security through global rate limiting and authentication.

** **Application Developer**: As an Application Developer, this lab will show you how to deploy the a **toystore** application, configure external access via an HTTPRoute, and secure it using Kuadrant policies for authentication and access control.

Overall, in this lab you install RHCL and understand how both platform engineers and application developers can effectively leverage RHCL to achieve their goals.

Duration: 2 hours

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Jaya Christina Baskaran
* Ravi Srinivasan
* Yogita Soni
* Rutuja Deshmukh
* Stephen McCarthy
* Anna Swicegood

== Objectives

On completing this course, you should be able to:

* Create and configure managed zone using AWS Route53.
* Install and deploy Kuadrant on a single-node Red Hat OpenShift cluster.
* Configure DNS and TLS for Kuadrant API Gateway, including AWS credentials and Let’s Encrypt setup.
* Implement essential RHCL gateway policies for managing API traffic like:
** DNS Policy
** TLS Policy
** Authentication policy
** Rate Limiting Policy
* Deploy toystore application as a developer.
* Configure external access via HTTPRoute.
* Secure the application using Kuadrant policies for authentication and access control.

== Prerequisites

This course assumes that you have the following prior experience:

1. https://training-lms.redhat.com/lmt/clmsCourseDetails.prMain?in_sessionId=103595A3J0989409&in_from_module=CLMSBROWSEV2.PRMAIN&in_offeringId=57857955[Red Hat OpenShift Container Platform (OCP) Technical Overview] or Kubernetes Basics
2. Basic Understanding of AWS services like EC2 and Route53
3. Basic knowledge of:

.TLS encryption: Click here for a quick primer
[%collapsible]
====
* TLS (Transport Layer Security) is a cryptographic protocol that ensures secure communication over a network.
====

.Rate limiting concepts: Click here for a quick primer
[%collapsible]
====
* Rate limiting controls how many requests a client can make to a server within a specific time frame.
* It is essential for protecting APIs, servers resources from being overwhelmed by excessive traffic, whether intentional (DDoS attacks) or unintentional (high demand).
====

.Authentication mechanisms (e.g., OAuth, JWT): Click here for a quick primer
[%collapsible]
====
* Authentication mechanisms validate the identity of a user or system attempting to access a resource.
* Example:
** OAuth (Open Authorization): OAuth is a standard for secure delegated access, allowing third-party applications to access resources on behalf of a user without exposing credentials.
====

.API and RESTful services: Click here for a quick primer
[%collapsible]
====
* API:
** An API is a set of rules and protocols that allow different software applications to communicate with each other.
** APIs enable developers to use predefined functions to interact with a service or application without needing to understand its internal workings.

* RESTful services:
** REST (Representational State Transfer) is an architectural style for designing networked applications.
** A RESTful service adheres to REST principles to provide scalability, simplicity, and statelessness.
====

.Service mesh architectures (like Istio): Click here for a quick primer
[%collapsible]
====
* A service mesh is a dedicated infrastructure layer for managing service-to-service communication in microservices architectures.
* It abstracts the network and provides advanced features like load balancing, traffic control, security, and observability.
====

