= Getting Started with Red Hat Connectivity Link
:navtitle: Home

== Introduction

Welcome to this quick course on the _Getting Started with Red Hat Connectivity Link_.
This course is the `second` in a series of `two` courses about Red Hat Connectivity Link.

The courses are as follows:

* https://xyz.com/[_Introduction to Red Hat Connectivity Link_]
* https://redhatquickcourses.github.io/rhcl-deploy/rhcl-deploy/1/index.html[_Getting Started with Red Hat Connectivity Link_]

In this hands-on lab, you will learn how to secure, protect, and connect an API through a Gateway based on the Kubernetes Gateway API, all within a single OpenShift cluster with a shared HTTPS listener. 

This lab is designed to use Red Hat Connectivity Link (RHCL) with a specific use case to implement its features, focusing on two different user roles:

* **Platform Engineer**: As a Platform Engineer, this lab will guide you through deploying a Gateway that ensures secure communication, making it ready for application development teams. You'll learn to route specific traffic while maintaining security through global rate limiting and authentication.

* **Application Developer**: As an Application Developer, this lab will show you how to deploy the a **toystore** application, configure external access via an HTTPRoute, and secure it using Kuadrant policies for authentication and access control.

Overall, this lab demonstrates how both platform engineers and application developers can effectively leverage RHCL to achieve their goals.

Duration: 2 hours

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Jaya Christina Baskaran
* Ravi Srinivasan
* Yogita Soni
* Rutuja Deshmukh

== Objectives

On completing this course, you should be able to:

* Hava a comprehensive overview of Red Hat Connectivity Link (RHCL) for hybrid cloud environments.
* Install and deploy Kuadrant on a single-node Red Hat OpenShift cluster.
* Configure DNS and TLS for Kuadrant API Gateway, including AWS credentials and Let’s Encrypt setup.
* Deploy toystore application as a developer.
* Configure external access via HTTPRoute.
* Secure the application using Kuadrant policies for authentication and access control.

== Prerequisites

This course assumes that you have the following prior experience:

* https://training-lms.redhat.com/lmt/clmsCourseDetails.prMain?in_sessionId=103595A3J0989409&in_from_module=CLMSBROWSEV2.PRMAIN&in_offeringId=57857955[Red Hat OpenShift Container Platform (OCP) Technical Overview]
