= Getting Started with Red Hat Connectivity Link
:navtitle: Home

== Introduction

Welcome to this quick course on the _Getting Started with Red Hat Connectivity Link_.
This course is the `second` in a series of `two` courses about Red Hat Connectivity Link (RHCL):

* https://xyz.com/[_Introduction to Red Hat Connectivity Link_]
* Getting Started with Red Hat Connectivity Link (_This course_)

== What's in this course?

* This lab is designed to use Red Hat Connectivity Link (RHCL) with a specific use case to implement its features, focusing on three different user roles:

** **Infrastructure Engineer**: As a Infrastructure Engineer, this lab will guide through Kuadrant installation and configuration.

** **Platform Engineer**: As a Platform Engineer, this lab will guide you through deploying a Gateway that ensures secure communication, making it ready for application development teams. You'll learn to route specific traffic while maintaining security through global rate limiting and authentication.

** **Application Developer**: As an Application Developer, this lab will show you how to deploy the a **toystore** application, configure external access via an HTTPRoute, and secure it using Kuadrant policies for authentication and access control.

Overall, in this lab you install RHCL and understand how both platform engineers and application developers can effectively leverage RHCL to achieve their goals.

Duration: 2 hours

== Contributors

The PTL team acknowledges the valuable contributions of the following Red Hat associates:

* Jaya Christina Baskaran
* Ravi Srinivasan
* Yogita Soni
* Rutuja Deshmukh
* Stephen McCarthy
* Anna Swicegood

== Objectives

On completing this course, you should be able to:

* Create and configure managed zone using AWS Route53.
* Install and deploy Kuadrant on a single-node Red Hat OpenShift cluster.
* Configure DNS and TLS for Kuadrant API Gateway, including AWS credentials and Let’s Encrypt setup.
* Implement essential RHCL gateway policies for managing API traffic like:
** DNS Policy
** TLS Policy
** Authentication policy
** Rate Limiting Policy
* Deploy toystore application as a developer.
* Configure external access via HTTPRoute.
* Secure the application using Kuadrant policies for authentication and access control.

== Prerequisites

This course assumes that you have the following prior experience:

* https://training-lms.redhat.com/lmt/clmsCourseDetails.prMain?in_sessionId=103595A3J0989409&in_from_module=CLMSBROWSEV2.PRMAIN&in_offeringId=57857955[Red Hat OpenShift Container Platform (OCP) Technical Overview] or Kubernetes Basics
* Familiarity with Red Hat Openshift networking concepts
* Basic Understanding of AWS services like EC2 and Route53
* Basic knowledge of TLS encryption, certificates (e.g., how they work), and certificate management tools.
* Concepts of DNS resolution, domain management, and how DNS policies work in cloud environments.
* Understanding rate limiting concepts, including request throttling, quotas, and burst limits.
* Familiarity with authentication mechanisms (e.g., OAuth, JWT) and how policies control access to APIs.
* Understanding API development, RESTful services, and how to define routes in Kubernetes.
* Familiarity with overriding default gateway policies (e.g., for authentication or rate limiting) based on application-specific needs.
* Knowledge of service mesh architectures (like Istio) and how they handle traffic routing, observability, and policy enforcement.
