:imagesdir: ../images

== Securing the Toystore Application with Connectivity Link Policies

In this lab exercise, you will configure authentication policies and generate API keys in the **toystore** application, which is secured by Connectivity Link policies.

. Create AuthPolicy
* Create policy for regular user by applying below yaml settings:
+
====
[source,subs="verbatim,quotes"]
----
**oc apply -f -<<EOF
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
 name: toystore-authn
 namespace: toystore
spec:
 targetRef:
   group: gateway.networking.k8s.io
   kind: HTTPRoute
   name: toystore
 defaults:
   strategy: merge
   rules:
     authentication:
       "api-key-authn":
         apiKey:
           selector:
             matchLabels:
               app: toystore
         credentials:
           authorizationHeader:
             prefix: APIKEY
EOF**
----
====
+
You should see the output as follows:
+
[source,subs="verbatim,quotes"]
----
authpolicy.kuadrant.io/toystore-authn created
----

* Create policy for admin user by applying below yaml settings:
+
====
[source,subs="verbatim,quotes"]
----
**oc apply -f -<<EOF
apiVersion: kuadrant.io/v1
kind: AuthPolicy
metadata:
 name: toystore-admins
 namespace: toystore
spec:
 targetRef:
   group: gateway.networking.k8s.io
   kind: HTTPRoute
   name: toystore
   sectionName: rule-2
 rules:
   authorization:
     "only-admins":
       opa:
         rego: |
           groups := split(object.get(input.auth.identity.metadata.annotations, "kuadrant.io/groups", ""), ",")
           allow { groups[_] == "admins" }
EOF**
----
====
+
You should see the output as follows:
+
[source,subs="verbatim,quotes"]
----
authpolicy.kuadrant.io/toystore-admins created
----

. Authenticate using API_KEY: The API_KEY is crucial for enforcing the security measures defined in the AuthPolicy and ensuring that the **toystore** application is accessed only by authenticated and authorized users.

* Create API Keys
** Create API keys for regular user roles by applying the following YAML file:
+
====
[source,subs="verbatim,quotes"]
----
**oc apply -f -<<EOF
apiVersion: v1
kind: Secret
metadata:
 name: api-key-regular-user
 namespace: kuadrant-system
 labels:
   authorino.kuadrant.io/managed-by: authorino
   app: toystore
stringData:
 api_key: iamaregularuser
type: Opaque
EOF**
----
====
+
You should see the output as follows:
+
[source,subs="verbatim,quotes"]
----
secret/api-key-regular-user created
----

** Next, create API keys for admin user roles by applying the following YAML file:
+
====
[source,subs="verbatim,quotes"]
----
**oc apply -f -<<EOF
apiVersion: v1
kind: Secret
metadata:
 name: api-key-admin-user
 namespace: kuadrant-system
 labels:
   authorino.kuadrant.io/managed-by: authorino
   app: toystore
 annotations:
   kuadrant.io/groups: admins
stringData:
 api_key: iamanadmin
type: Opaque
EOF**
----
====
+
You should see the output as follows:
+
[source,subs="verbatim,quotes"]
----
secret/api-key-admin-user created
----
